# NB 白名单(当前调试版)
# 仅在白名单通过后，程序才会进入 TikTok 内部分流分类器

domain tiktok.com
domain tiktokv.com
domain tiktokv.us
domain tiktokcdn.com
domain tiktokcdn.us
domain tiktokcdn-us.com
domain byteoversea.com
domain ibyteimg.com
domain tiktok-row.net
domain ttwstatic.com
domain musical.ly
domain ipinfo.io
domain ip.sb
domain google.com
domain baidu

port 443
port 80
port 50000
port 50001
port 50008
port 50009
port 50020
port 50021
