/*
 * ioctls.h - IOCTL 码定义
 */

#pragma once

// 设备类型
#define FILE_DEVICE_PERSONAL_SAFER 0x8000

// IOCTL 码定义
// 方向: 驱动 -> 用户 (FILE_ANY_ACCESS 的 buffered/ioctl 方式)
#define IOCTL_PS_FILE_EVENT \
    CTL_CODE(FILE_DEVICE_PERSONAL_SAFER, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PS_NET_EVENT \
    CTL_CODE(FILE_DEVICE_PERSONAL_SAFER, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

// 方向: 用户 -> 驱动
#define IOCTL_PS_DRIVER_START \
    CTL_CODE(FILE_DEVICE_PERSONAL_SAFER, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PS_DRIVER_STOP \
    CTL_CODE(FILE_DEVICE_PERSONAL_SAFER, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PS_SET_POLICY \
    CTL_CODE(FILE_DEVICE_PERSONAL_SAFER, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PS_GET_POLICY \
    CTL_CODE(FILE_DEVICE_PERSONAL_SAFER, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PS_DRIVER_STATUS \
    CTL_CODE(FILE_DEVICE_PERSONAL_SAFER, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PS_HEARTBEAT \
    CTL_CODE(FILE_DEVICE_PERSONAL_SAFER, 0x807, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PS_SET_QUARANTINE \
    CTL_CODE(FILE_DEVICE_PERSONAL_SAFER, 0x808, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PS_GET_QUARANTINE \
    CTL_CODE(FILE_DEVICE_PERSONAL_SAFER, 0x809, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PS_SET_REDIRECT \
    CTL_CODE(FILE_DEVICE_PERSONAL_SAFER, 0x80A, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PS_QUERY_REDIRECT \
    CTL_CODE(FILE_DEVICE_PERSONAL_SAFER, 0x80B, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PS_FILE_EVENT_BATCH \
    CTL_CODE(FILE_DEVICE_PERSONAL_SAFER, 0x80C, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PS_NET_EVENT_BATCH \
    CTL_CODE(FILE_DEVICE_PERSONAL_SAFER, 0x80D, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PS_WAIT_EVENTS \
    CTL_CODE(FILE_DEVICE_PERSONAL_SAFER, 0x80E, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PS_SET_PROTECT_LIST \
    CTL_CODE(FILE_DEVICE_PERSONAL_SAFER, 0x80F, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PS_GET_PROTECT_CHALLENGE \
    CTL_CODE(FILE_DEVICE_PERSONAL_SAFER, 0x810, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PS_UNLOCK_PROTECTION \
    CTL_CODE(FILE_DEVICE_PERSONAL_SAFER, 0x811, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PS_RELOCK_PROTECTION \
    CTL_CODE(FILE_DEVICE_PERSONAL_SAFER, 0x812, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PS_QUERY_PROTECT_STATE \
    CTL_CODE(FILE_DEVICE_PERSONAL_SAFER, 0x813, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PS_PROTECT_CONTROL \
    CTL_CODE(FILE_DEVICE_PERSONAL_SAFER, 0x814, METHOD_BUFFERED, FILE_ANY_ACCESS)
