/*
 * ioctls.h - IOCTL 码定义
 */

#pragma once

// 设备类型
#define FILE_DEVICE_PERSONAL_SAFER 0x8000

// IOCTL access is part of the security boundary. Telemetry/query calls only
// require a read handle; every state-changing call requires a write handle.
#define PS_IOCTL_READ(code) \
    CTL_CODE(FILE_DEVICE_PERSONAL_SAFER, code, METHOD_BUFFERED, FILE_READ_ACCESS)
#define PS_IOCTL_CONTROL(code) \
    CTL_CODE(FILE_DEVICE_PERSONAL_SAFER, code, METHOD_BUFFERED, FILE_WRITE_ACCESS)

#define IOCTL_PS_FILE_EVENT \
    PS_IOCTL_READ(0x800)

#define IOCTL_PS_NET_EVENT \
    PS_IOCTL_READ(0x801)

// 方向: 用户 -> 驱动
#define IOCTL_PS_DRIVER_START \
    PS_IOCTL_CONTROL(0x802)

#define IOCTL_PS_DRIVER_STOP \
    PS_IOCTL_CONTROL(0x803)

#define IOCTL_PS_SET_POLICY \
    PS_IOCTL_CONTROL(0x804)

#define IOCTL_PS_GET_POLICY \
    PS_IOCTL_READ(0x805)

#define IOCTL_PS_DRIVER_STATUS \
    PS_IOCTL_READ(0x806)

#define IOCTL_PS_HEARTBEAT \
    PS_IOCTL_READ(0x807)

#define IOCTL_PS_SET_QUARANTINE \
    PS_IOCTL_CONTROL(0x808)

#define IOCTL_PS_GET_QUARANTINE \
    PS_IOCTL_READ(0x809)

#define IOCTL_PS_SET_REDIRECT \
    PS_IOCTL_CONTROL(0x80A)

#define IOCTL_PS_QUERY_REDIRECT \
    PS_IOCTL_READ(0x80B)

#define IOCTL_PS_FILE_EVENT_BATCH \
    PS_IOCTL_READ(0x80C)

#define IOCTL_PS_NET_EVENT_BATCH \
    PS_IOCTL_READ(0x80D)

#define IOCTL_PS_WAIT_EVENTS \
    PS_IOCTL_READ(0x80E)

#define IOCTL_PS_SET_PROTECT_LIST \
    PS_IOCTL_CONTROL(0x80F)

#define IOCTL_PS_GET_PROTECT_CHALLENGE \
    PS_IOCTL_CONTROL(0x810)

#define IOCTL_PS_UNLOCK_PROTECTION \
    PS_IOCTL_CONTROL(0x811)

#define IOCTL_PS_RELOCK_PROTECTION \
    PS_IOCTL_CONTROL(0x812)

#define IOCTL_PS_QUERY_PROTECT_STATE \
    PS_IOCTL_READ(0x813)

#define IOCTL_PS_PROTECT_CONTROL \
    PS_IOCTL_CONTROL(0x814)
